---
#  Copyright (c) 2018 Red Hat, Inc.
#
#  This file is part of ARA Records Ansible.
#
#  ARA is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ARA is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ARA.  If not, see <http://www.gnu.org/licenses/>.

- name: Ensure the embedded server service is not started and is disabled
  become: true
  systemd:
    name: ara
    state: stopped
    enabled: no
    masked: yes

- name: install ondrej apache repo for Ubuntu
  apt_repository:
    repo: ppa:ondrej/apache2
    update_cache: yes
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install required dependencies for mod_wsgi
  become: true
  package:
    name: "{{ required_wsgi_packages }}"
    state: "present"

- name: Set selinux boolean to allow Apache to manage the files
  become: true
  seboolean:
    name: httpd_unified
    state: yes
  when: ansible_os_family == "RedHat"

- name: Get the location of the WSGI script
  command: which ara-wsgi
  environment:
    PATH: "{{ path_with_virtualenv | default(lookup('env','PATH')) }}"
  register: wsgi_location
  changed_when: false

- name: Set the location of the WSGI script
  set_fact:
    wsgi_script: "{{ wsgi_location.stdout }}"

- name: Set up Apache configuration
  become: true
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ apache_config_path }}/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  loop:
    - ara-wsgi
    - ara-wsgi-ssl
  notify:
    - restart apache

- name: Ensure Apache server is started
  become: true
  systemd:
    state: started
    name: "{{ apache_service }}"
    enabled: true

- import_tasks: apache/ssl.yml
  when: ara.deployment.apache.ssl == true

- name: Ensure the configuration is enabled for http
  become: true
  file:
    src: /etc/apache2/sites-available/ara-wsgi.conf
    dest: /etc/apache2/sites-enabled/ara-wsgi.conf
    owner: root
    group: root
    state: link
  when: ansible_os_family == "Debian" and ara.deployment.apache.ssl != true
  notify:
    - restart apache
